ORGS_exp=(
"org1:eyJrIjoiMTlTTE9hRjI1bXpsNXNUR2ZBSmpHQkhTNnVpNzJHTUsiLCJuIjoiZ3JhZmFuYV9leHBvcnQiLCJpZCI6MX0="
)
HOST_exp="https://grafana7.dev.sdil.aorta.net"
FILE_DIR_exp=/home/ansible/git/obs-infrastructure/roles/grafana-user-dashboard/files/grafana-user-dashboard/sources
ORGS=(
"org1:eyJrIjoiWUxyVVdSSW9ZWmt5aDF3SWw4M0dQODlZcThVc2J4dVoiLCJuIjoiZ3JhZmFuYV9leHBvcnQiLCJpZCI6MX0="
)
HOST="https://grafana7.sdil.aorta.net"
FILE_DIR=/home/ansible/git/obs-infrastructure/roles/grafana-user-dashboard/files/grafana-user-dashboard/sources
